apps/blog/urls.py
from django.urls import path
from .views import blog, details_blog

urlpatterns = [
    path('blog/', blog, name="pagina_blog"),
    path('blog/<int:blog_id>', details_blog, name="blog_detalhes"),

]

apps/core/urls.py
from django.contrib import admin

from django.urls import path, include
from .views import create_user, entrar, sair

urlpatterns = [
    path('create_user', create_user, name="create_user"),
    path('entrar', entrar, name="entrar"),
    path('sair', sair, name="sair"),
]

apps/jobs/urls.py
from django.urls import path
from .views import job, jobs, create_job, update_job, delete_job

urlpatterns = [

    path('', jobs, name="pagina_jobs"),
    path('/<int:id>/', job, name="ver_job"),
    path('update/<int:job_id>/', update_job, name="update_job"),
    path('create_job/', create_job, name="pagina_jobs_create_job"),
    path('delete_job/<int:job_id>/', delete_job, name="delete_job"),

]

arq_vagas/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.core.views import *
from apps.blog.views import *
from apps.jobs.views import *

# http://127.0.0.1:8000/

urlpatterns = [
    # http://127.0.0.1:8000/admin/
    path('admin/', admin.site.urls),
    path('core/', include('apps.core.urls')),
    path('jobs/', include('apps.jobs.urls')),
    path('blog/', include('apps.blog.urls')),
    # http://127.0.0.1:8000/
    path('', home, name="pagina_home"),
    path('grappelli/', include('grappelli.urls')),
]

apps/blog/models.py
from django.db import models

class Noticia(models.Model):
    titulo_noticia = models.CharField(max_length=200)
    conteudo_noticia = models.TextField()

    def __str__(self):
        return self.titulo_noticia

apps/core/models.py
from django.db import models

# Create your models here.
class Configuracao(models.Model):
    slogan = models.CharField(max_length=50)
    nome_empresa = models.CharField(max_length=20)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return self.nome_empresa

apps/jobs/models.py
from django.db import models


# Create your models here.
class Job(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True)
    nome = models.CharField(max_length=100)
    empresa = models.CharField(max_length=100)
    salario = models.DecimalField(max_digits=10, decimal_places=2)
    cidade = models.CharField(max_length=50)
    qtd_jobs = models.IntegerField()

    def __str__(self):
        return self.nome

apps/core/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label='Nome de usuário', max_length=100)
    password = forms.CharField(label='Senha', max_length=100, widget=forms.PasswordInput)

    class Meta:
        fields = ['username', 'password']

apps/jobs/forms.py
from django import forms

from apps.jobs.models import Job


class JobUpdateForm(forms.ModelForm):
    salario = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)

    class Meta:
        model = Job
        fields = '__all__'


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ['user', ]

    def save(self, commit=False, user=None):
        job = super(JobForm, self).save(commit=False)
        job.user = user
        commit = True
        if commit:
            job.save()
        return job

apps/blog/views.py
from django.shortcuts import render
from .models import Noticia


# Create your views here.
def blog(request):
    lista_noticias = Noticia.objects.all()
    dados = {
        "noticias": lista_noticias
    }
    return render(request, "blog.html", dados)


def details_blog(request, blog_id):
    busca_id = Noticia.objects.get(id=blog_id)
    dados = {
        "noticia": busca_id
    }
    return render(request, "blog_details.html", dados)

apps/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from .models import Configuracao


def home(request):
    configuracao = Configuracao.objects.all()

    # Esta verificação é apenas para não deixar o site em branco
    if len(configuracao) > 0:
        configuracao = configuracao[0]
    else:
        configuracao = {
            "slogan": "Slogan",
            "nome_empresa": "Nome da Empresa",
            "telefone": "(00) 00000-0000",
            "email": "email@amil.com"
        }

    dados = {
        "configuracao": configuracao,
    }
    return render(request, "home.html", dados)


def create_user(request):
    form = UserForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        User.objects.create_user(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        return redirect('entrar')
    return render(request, "create_user.html", {'form': form})


def entrar(request):
    form = UserForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('pagina_home')
        else:
            form.add_error(None, 'Nome de usuário ou senha incorretos')
    return render(request, "login.html", {'form': form})


@login_required(login_url='core/entrar')
def sair(request):
    logout(request)
    return redirect('pagina_home')

apps/jobs/views.py
import pprint

from django.shortcuts import render, redirect, get_object_or_404

from .forms import JobForm, JobUpdateForm
from .models import Job


# Create your views here.
def jobs(request):
    jobs = Job.objects.all()

    dados = {
        "jobs": jobs
    }
    return render(request, "jobs.html", dados)


def job(request, id):
    job = Job.objects.get(id=id)
    dados = {
        "job": job
    }
    return render(request, "vaga.html", dados)


def create_job(request):
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            if request.user.is_authenticated:
                form.save(user=request.user)
                return redirect('pagina_jobs')
            else:
                form.add_error(None, 'User not authenticated')
    else:
        form = JobForm()
    return render(request, "criar_vaga.html", {'form': form})


def update_job(request, job_id):
    instance = get_object_or_404(Job, id=job_id)
    form = JobUpdateForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('pagina_jobs')
    else:
        print(form.errors)
    return render(request, "atualizar_vaga.html", {'form': form,
                                                   'instance': instance})


def delete_job(request, job_id):
    instance = get_object_or_404(Job, id=job_id)
    instance.delete()
    return redirect('pagina_jobs')

templates/atualizar_vaga.html
{% extends "base.html" %}
{% load static %}
{% block conteudo %}
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/jobs.css' %}">
    {% endblock %}
    <div class="center-div">
        <h1>Atualizar Job - {{ instance.nome }}</h1>
        {% if form.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <li><strong>{{ field }}:</strong> {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_user">Usuário:</label>
                <select id="id_user" name="user">
                    {% for user in form.fields.user.queryset %}
                        <option value="{{ user.pk }}" {% if user.pk == form.instance.user.pk %}selected{% endif %}>
                            {{ user.username }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="id_nome">Nome:</label>
                <input type="text" id="id_nome" name="nome" value="{{ form.nome.value|default:'' }}">
            </div>
            <div class="form-group">
                <label for="id_empresa">Empresa:</label>
                <input type="text" id="id_empresa" name="empresa" value="{{ form.empresa.value|default:'' }}">
            </div>
            <div class="form-group">
                <label for="id_salario">Salário:</label>
                <input type="text" id="id_salario" name="salario" value="{{ form.salario.value|default:'' }}">
            </div>
            <div class="form-group">
                <label for="id_cidade">Cidade:</label>
                <input type="text" id="id_cidade" name="cidade" value="{{ form.cidade.value|default:'' }}">
            </div>
            <div class="form-group">
                <label for="id_qtd_jobs">Quantidade de vagas:</label>
                <input type="text" id="id_qtd_jobs" name="qtd_jobs" value="{{ form.qtd_jobs.value|default:'' }}">
            </div>
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {# 1 - ADICIONADO ESTILO#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600;700&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block titulo %}{% endblock %}</title>
    {% block css %}{% endblock %}
</head>
<body>
    {# Carregando... #}
    <div class="pxp-preloader"><span>Carregando...</span></div>

{#   INICIO NAVBAR #}
    <header class="pxp-header fixed-top pxp-no-bg pxp-bigger">
            <div class="pxp-container">
                <div class="pxp-header-container">
                    <div class="pxp-logo-nav-container">
                        <div class="pxp-logo">
                            <a href="index.html" class="pxp-animate"><span style="color: var(--pxpMainColor)">j</span>obster</a>
                        </div>
                        <div class="pxp-nav-trigger navbar d-xl-none flex-fill">
                            <a role="button" data-bs-toggle="offcanvas" data-bs-target="#pxpMobileNav" aria-controls="pxpMobileNav">
                                <div class="pxp-line-1"></div>
                                <div class="pxp-line-2"></div>
                                <div class="pxp-line-3"></div>
                            </a>
                            <div class="offcanvas offcanvas-start pxp-nav-mobile-container" tabindex="-1" id="pxpMobileNav">
                                <div class="offcanvas-header">
                                    <div class="pxp-logo">
                                        <a href="index.html" class="pxp-animate"><span style="color: var(--pxpMainColor)">j</span>obster</a>
                                    </div>
                                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                                </div>
                                <div class="offcanvas-body">
                                    <nav class="pxp-nav-mobile">
                                        <ul class="navbar-nav justify-content-end flex-grow-1">
                                            <li class="nav-item dropdown">
                                                <a role="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Home</a>
                                            </li>
                                            <li class="nav-item dropdown">
                                                <a role="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Find Jobs</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                        <nav class="pxp-nav dropdown-hover-all d-none d-xl-block">
                            <ul>
                                <li>
                                    <a href="{% url 'pagina_home' %}">Home</a>
                                </li>
                                <li>
                                    <a href="{% url 'pagina_blog' %}">Blog</a>
                                </li>
                                <li>
                                    <a href="{% url 'pagina_jobs' %}">Vagas</a>
                                </li>

                            </ul>
                        </nav>
                    </div>
                    <nav class="pxp-user-nav pxp-on-light gap-3">
                        <a href="#" class="btn rounded-pill pxp-nav-btn">Criar vaga</a>
                        {% if user.is_authenticated %}#}
                        <div class="dropdown pxp-user-nav-dropdown">
                            <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                                <div class="pxp-user-nav-avatar pxp-cover" style="background-image: url({% static 'images/ph-small.jpg' %});"></div>
                                <div class="pxp-user-nav-name d-none d-md-block">{{ user.username }}</div>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item" href="{% url 'sair' %}">Logout</a></li>
                            </ul>
                        </div>
                        {% else %}
                            <a href="{% url 'entrar' %}" class="btn rounded-pill pxp-nav-btn">Login</a>
                        {% endif %}

                    </nav>
                </div>
            </div>
        </header>


{#    FIM NAVBAR   #}



{#    <div class="header">#}
{#        <div class="nav-links">#}
{#            <a href="{% url 'pagina_home' %}">Home</a>#}
{#            <a href="{% url 'pagina_blog' %}">Blog</a>#}
{#            <a href="{% url 'pagina_jobs' %}">Jobs</a>#}
{#        </div>#}
{##}
{#        {% if user.is_authenticated %}#}
{#            <p>Olá, {{ user.username }}!</p>#}
{#            <a href="{% url 'sair' %}">Logout</a>#}
{#        {% else %}#}
{#            <a href="{% url 'entrar' %}">Login</a>#}
{#        {% endif %}#}
{#    </div>#}

    {% block conteudo %}{% endblock %}


{#    INICIO FOOTER #}
            <footer class="pxp-main-footer mt-100">
            <div class="pxp-main-footer-bottom" style="background-color: var(--pxpSecondaryColor);">
                <div class="pxp-container">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-lg-auto">
                            <div class="pxp-footer-copyright pxp-text-light">© 2023 Jobster. Todos os direitos reservados.</div>
                        </div>
                        <div class="col-lg-auto">
                            <div class="pxp-footer-social mt-3 mt-lg-0">
                                <ul class="list-unstyled">
                                    <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                    <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                    <li><a href="#"><span class="fa fa-instagram"></span></a></li>
                                    <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <div class="modal fade pxp-user-modal" id="pxp-signin-modal" aria-hidden="true" aria-labelledby="signinModal" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="pxp-user-modal-fig text-center">
                            <img src="images/signin-fig.png" alt="Sign in">
                        </div>
                        <h5 class="modal-title text-center mt-4" id="signinModal">Welcome back!</h5>
                        <form class="mt-4">
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" id="pxp-signin-email" placeholder="Email address">
                                <label for="pxp-signin-email">Email address</label>
                                <span class="fa fa-envelope-o"></span>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" id="pxp-signin-password" placeholder="Password">
                                <label for="pxp-signin-password">Password</label>
                                <span class="fa fa-lock"></span>
                            </div>
                            <a href="#" class="btn rounded-pill pxp-modal-cta">Continue</a>
                            <div class="mt-4 text-center pxp-modal-small">
                                <a href="#" class="pxp-modal-link">Forgot password</a>
                            </div>
                            <div class="mt-4 text-center pxp-modal-small">
                                New to Jobster? <a role="button" class="" data-bs-target="#pxp-signup-modal" data-bs-toggle="modal" data-bs-dismiss="modal">Create an account</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade pxp-user-modal" id="pxp-signup-modal" aria-hidden="true" aria-labelledby="signupModal" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="pxp-user-modal-fig text-center">
                            <img src="images/signup-fig.png" alt="Sign up">
                        </div>
                        <h5 class="modal-title text-center mt-4" id="signupModal">Create an account</h5>
                        <form class="mt-4">
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" id="pxp-signup-email" placeholder="Email address">
                                <label for="pxp-signup-email">Email address</label>
                                <span class="fa fa-envelope-o"></span>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" id="pxp-signup-password" placeholder="Create password">
                                <label for="pxp-signup-password">Create password</label>
                                <span class="fa fa-lock"></span>
                            </div>
                            <a href="#" class="btn rounded-pill pxp-modal-cta">Continue</a>
                            <div class="mt-4 text-center pxp-modal-small">
                                Already have an account? <a role="button" class="" data-bs-target="#pxp-signin-modal" data-bs-toggle="modal">Sign in</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{#    FIM FOOTER   #}

    {# 2 - ADICIONADO JAVASCRIPT #}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/blog.html
{% extends "base.html" %}

{% block titulo %}Blog{% endblock %}

{% block titulo_body %}Arq - Blog{% endblock %}

{% block conteudo %}

    <section>
            <div class="pxp-container">
                <div class="row justify-content-center">
                    <div class="col-xl-9">
                        <div class="pxp-blog-hero">
                            <h1 class="text-center">Noticias</h1>
                            <div class="pxp-hero-subtitle pxp-text-light text-center">Todas as noticias do blog</div>
                        </div>
                        <div class="mt-1 mt-lg-1">
                            <div class="row">
                                {% for noticia in noticias %}
                                <div class="col-md-6 col-xxl-4 pxp-posts-card-1-container">
                                    <div class="pxp-posts-card-1 pxp-has-border">
                                        <div class="pxp-posts-card-1-top">
                                            <div class="pxp-posts-card-1-top-bg">
                                                <div class="pxp-posts-card-1-image pxp-cover" style="background-image: url('https://shorturl.at/bkvS0');"></div>
                                            </div>
                                            <div class="pxp-posts-card-1-content">
                                                <a href="single-blog-post.html" class="pxp-posts-card-1-title">{{noticia.titulo_noticia}}</a>
                                                <div class="pxp-posts-card-1-summary pxp-text-light">{{noticia.conteudo_noticia}}</div>
                                            </div>
                                        </div>
                                        <div class="pxp-posts-card-1-bottom">
                                            <div class="pxp-posts-card-1-cta">
                                                <a href="{% url 'blog_detalhes' noticia.id %}">Saiba mais<span class="fa fa-angle-right"></span></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

templates/blog_details.html
{% extends "base.html" %}

{% block titulo %}Blog{% endblock %}

{% block titulo_body %}Arq - Blog{% endblock %}

{% block conteudo %}

{#        <div width="40%" height="auto">#}
{#            <h2>{{noticia.titulo_noticia}}</h2>#}
{#            <p>{{noticia.conteudo_noticia}}</p>#}
{#        </div>#}

        <section>
            <div class="pxp-container">
                <div class="pxp-blog-hero">
                    <div class="row justify-content-between align-items-end">
                        <div class="col-lg-8 col-xxl-6">
                            <h1>{{noticia.titulo_noticia}}</h1>
                            <div class="pxp-hero-subtitle pxp-text-light">Subtitulo</div>
                        </div>
                        <div class="col-lg-4 col-xxl-6">
                            <div class="text-start text-lg-end mt-4 mt-lg-0">
                                <div class="pxp-single-blog-top-category">
                                    Postado <a href="#">29/09/2023</a>
                                </div>
                                <div class="pxp-single-blog-top-author">
                                    por <a href="blog-list-1.html">Ramonzinho</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="mt-100">
            <div class="pxp-container">
                <div class="row justify-content-center">
                    <div class="col-xl-7">
                        <div class="pxp-single-blog-content">
                            {{noticia.conteudo_noticia}}
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

templates/create_user.html
<h1>Criando a conta</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>

templates/criar_vaga.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

templates/home.html
{% extends "base.html" %}

{% block titulo %}Home Page{% endblock %}

{% block titulo_body %}
    {{ configuracao.slogan }}
{% endblock %}


{% block conteudo %}
{#    <ul>#}
{#        <li>{{ configuracao.nome_empresa }}</li>#}
{#        <li>{{ configuracao.telefone }}</li>#}
{#        <li>{{ configuracao.email }}</li>#}
{#    </ul>#}

    <section>
            <div class="pxp-container">
                <div class="pxp-single-company-container">
                    <div class="row justify-content-center">
                        <div class="col-xl-9">
                            <div class="pxp-single-company-hero pxp-cover pxp-boxed" style="background-image: url(images/ph-big.jpg);">
                                <div class="pxp-hero-opacity"></div>
                                <div class="pxp-single-company-hero-caption">
                                    <div class="pxp-single-company-hero-content d-block text-center">
                                        <div class="pxp-single-company-hero-logo d-inline-block" style="background-image: url(images/company-logo-3.png);"></div>
                                        <div class="pxp-single-company-hero-title ms-0 mt-3">
                                            <h1>{{ configuracao.nome_empresa }}</h1>
                                            <div class="pxp-single-company-hero-location"><span class="fa fa-globe"></span>Teresina, Piauí</div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-4 mt-lg-5">
                                <div class="col-lg-7 col-xxl-8">
                                    <div class="pxp-single-company-content">
                                        <h2>Sobre {{ configuracao.nome_empresa }}</h2>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the </p>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the </p>
                                    </div>
                                </div>
                                <div class="col-lg-5 col-xxl-4">
                                    <div class="pxp-single-company-side-panel mt-5 mt-lg-0">
                                        <div class="mt-4">
                                            <div class="pxp-single-company-side-info-label pxp-text-light">Setor</div>
                                            <div class="pxp-single-company-side-info-data">Software</div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="pxp-single-company-side-info-label pxp-text-light">Porte da Empresa</div>
                                            <div class="pxp-single-company-side-info-data">50-100</div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="pxp-single-company-side-info-label pxp-text-light">Fundado em</div>
                                            <div class="pxp-single-company-side-info-data">2005</div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="pxp-single-company-side-info-label pxp-text-light">Contato</div>
                                            <div class="pxp-single-company-side-info-data">0124 456 789</div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="pxp-single-company-side-info-label pxp-text-light">Email</div>
                                            <div class="pxp-single-company-side-info-data">office@illuminate-st.com</div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="pxp-single-company-side-info-label pxp-text-light">Endereço</div>
                                            <div class="pxp-single-company-side-info-data">San Francisco, CA</div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="pxp-single-company-side-info-label pxp-text-light">Site</div>
                                            <div class="pxp-single-company-side-info-data"><a href="#">www.illuminate-st.com</a></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}